blueprint:
  name: EV Load Management (Safe Start, House Power Based)
  description: >
    Dinamično polnjenje EV glede na porabo hiše in tarifni blok.
    - Avtomatizacija se zažene ob priklopu vozila (Idle → Active)
    - Polnilnica se vklopi ŠELE, ko je dovolj moči za 6A + buffer
    - Tok se dinamično prilagaja (6A–maxA), buffer le pri povečanju
    - Če ni dovolj moči za 6A → tok = 0A (polnjenje začasno ustavljeno)
    - Seja ostane aktivna, polnjenje se nadaljuje ob prosti moči
    - Avtomatizacija se ustavi ob State A - Idle
  domain: automation

  input:
    export_sensor:
      name: Export / House Power Sensor (W)
      selector:
        entity:
          domain: sensor
    charger_switch:
      name: Charger switch
      selector:
        entity:
          domain: switch
    charger_current:
      name: Charger current (A)
      selector:
        entity:
          domain: number
    charging_state:
      name: Charger state sensor
      selector:
        entity:
          domain: sensor
    tariff_block:
      name: Current tariff block sensor (1–5)
      selector:
        entity:
          domain: sensor
    block_limit_1:
      name: Block 1 limit (W)
      default: 6000
      selector:
        number:
          min: 0
          max: 25000
          step: 100
    block_limit_2:
      name: Block 2 limit (W)
      default: 6000
      selector:
        number:
          min: 0
          max: 25000
          step: 100
    block_limit_3:
      name: Block 3 limit (W)
      default: 6000
      selector:
        number:
          min: 0
          max: 25000
          step: 100
    block_limit_4:
      name: Block 4 limit (W)
      default: 6000
      selector:
        number:
          min: 0
          max: 25000
          step: 100
    block_limit_5:
      name: Block 5 limit (W)
      default: 6000
      selector:
        number:
          min: 0
          max: 25000
          step: 100
    buffer:
      name: Buffer for start/hysteresis (W)
      default: 500
      selector:
        number:
          min: 0
          max: 2000
          step: 100
    max_current:
      name: Maximum current (A)
      default: 16
      selector:
        number:
          min: 6
          max: 32
          step: 1
    debug:
      name: Debug log
      default: false
      selector:
        boolean: {}

triggers:
  - trigger: state
    entity_id: !input charging_state
    from: "State A - Idle"

actions:
  - variables:
      export_sensor_entity: !input export_sensor
      charger_switch_entity: !input charger_switch
      charger_current_entity: !input charger_current
      charging_state_entity: !input charging_state
      tariff_block_entity: !input tariff_block
      buffer: !input buffer
      min_amp: 6  # FIKSNO 6A – ni nastavljivo
      max_amp: !input max_current
      debug: !input debug
      power_per_amp: 690  # 3-fazno: 230V × 3

  - repeat:
      while:
        - condition: template
          value_template: "{{ not is_state(charging_state_entity, 'State A - Idle') }}"
      sequence:
        - variables:
            export_raw: "{{ states(export_sensor_entity) | float(default=0) }}"
            current_block: "{{ states(tariff_block_entity) | int(1) }}"
            block_limits:
              1: !input block_limit_1
              2: !input block_limit_2
              3: !input block_limit_3
              4: !input block_limit_4
              5: !input block_limit_5
            block_limit: "{{ block_limits.get(current_block, 6000) | float(6000) }}"
            current_amp: "{{ states(charger_current_entity) | float(default=min_amp) }}"
            step_amp: >-
              {% set diff = (block_limit - export_raw) / power_per_amp %}
              {{ [1, [diff | abs | round(0), 6] | min] | max }}
            available_power: "{{ block_limit - export_raw }}"

        ################################################################
        # VARNA LOGIKA VKLOPA – ENOTEN POGOJ Z BUFFERJEM
        ################################################################
        - choose:
            - conditions:
                - condition: state
                  entity_id: !input charger_switch
                  state: "off"
                - condition: template
                  value_template: >
                    {{ export_raw | float(0) < (block_limit - buffer) and (block_limit - export_raw | float(0)) >= (min_amp * 230 * 3) }}
              sequence:
                - action: switch.turn_on
                  target:
                    entity_id: !input charger_switch
                - delay: 2
                - action: number.set_value
                  target:
                    entity_id: !input charger_current
                  data:
                    value: "{{ min_amp }}"
                - choose:
                    - conditions:
                        - condition: template
                          value_template: "{{ debug }}"
                      sequence:
                        - action: system_log.write
                          data:
                            level: warning
                            message: "[EV DEBUG] START → Charger ON (enough power for 6A + buffer)"

        ################################################################
        # PRILAGAJANJE TOKA – POLNILNICA VEDNO VKLOPLJENA
        ################################################################
        - choose:
            - conditions:
                - condition: state
                  entity_id: !input charger_switch
                  state: "on"
              sequence:

                # 1. ZMANJŠAJ na 0A, če ni dovolj moči za 6A
                - choose:
                    - conditions:
                        - condition: template
                          value_template: >
                            {{ export_raw > block_limit and current_amp >= min_amp }}
                      sequence:
                        - action: number.set_value
                          target:
                            entity_id: !input charger_current
                          data:
                            value: 0
                        - choose:
                            - conditions:
                                - condition: template
                                  value_template: "{{ debug }}"
                              sequence:
                                - action: system_log.write
                                  data:
                                    level: warning
                                    message: "[EV DEBUG] PAUSE → Not enough power, current = 0A"

                # 2. POVZROČI na 6A, če je dovolj moči (enak pogoj kot vklop!)
                - choose:
                    - conditions:
                        - condition: template
                          value_template: >
                            {{ export_raw | float(0) < (block_limit - buffer) and (block_limit - export_raw | float(0)) >= (min_amp * 230 * 3) and current_amp == 0 }}
                      sequence:
                        - action: number.set_value
                          target:
                            entity_id: !input charger_current
                          data:
                            value: "{{ min_amp }}"
                        - choose:
                            - conditions:
                                - condition: template
                                  value_template: "{{ debug }}"
                              sequence:
                                - action: system_log.write
                                  data:
                                    level: warning
                                    message: "[EV DEBUG] RESUME → Enough power, current = 6A"

                # 3. POVZROČI nad 6A (z bufferjem)
                - choose:
                    - conditions:
                        - condition: template
                          value_template: >
                            {{ export_raw < (block_limit - buffer) and current_amp >= min_amp and current_amp < max_amp }}
                      sequence:
                        - action: number.set_value
                          target:
                            entity_id: !input charger_current
                          data:
                            value: "{{ [ (current_amp|int + step_amp|int), max_amp ] | min }}"

                # 4. ZMANJŠAJ pod max (brez bufferja)
                - choose:
                    - conditions:
                        - condition: template
                          value_template: >
                            {{ export_raw > block_limit and current_amp > min_amp }}
                      sequence:
                        - action: number.set_value
                          target:
                            entity_id: !input charger_current
                          data:
                            value: "{{ [ (current_amp|int - step_amp|int), min_amp ] | max }}"

        ################################################################
        # DEBUG LOG
        ################################################################
        - choose:
            - conditions:
                - condition: template
                  value_template: "{{ debug }}"
              sequence:
                - action: system_log.write
                  data:
                    level: warning
                    message: >
                      [EV DEBUG] Block={{ current_block }}, Limit={{ block_limit }}W,
                      Export={{ export_raw }}W, Avail={{ available_power }}W,
                      CurrAmp={{ current_amp }}A, Step={{ step_amp }}

        - delay:
            seconds: 30

  ################################################################
  # KONEC SEJE: State A - Idle → izklop
  ################################################################
  - action: switch.turn_off
    target:
      entity_id: !input charger_switch
  - action: number.set_value
    target:
      entity_id: !input charger_current
    data:
      value: 0
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ debug }}"
        sequence:
          - action: system_log.write
            data:
              level: warning
              message: "[EV DEBUG] STOP → State A - Idle, charging stopped"

mode: restart
